# Generated by Django 3.1.3 on 2020-11-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo Imagen',
                'verbose_name_plural': 'Tipos de Imagen',
            },
        ),
    ]
