# Generated by Django 3.1.3 on 2020-11-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Estudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion_corta', models.TextField()),
                ('descripcion_larga', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono', models.CharField(max_length=20)),
                ('orientado_a', models.CharField(max_length=255)),
                ('otorga', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Unidad_Estudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pachaqtec.plan_estudio')),
            ],
            options={
                'verbose_name': 'Unidad de Estudio',
                'verbose_name_plural': 'Unidades de Estudio',
            },
        ),
        migrations.CreateModel(
            name='Sub_Unidad_Estudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField(verbose_name=1)),
                ('posicion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('unidad_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pachaqtec.unidad_estudio')),
            ],
            options={
                'verbose_name': 'Sub Unidad de Estudio',
                'verbose_name_plural': 'Sub Unidades de Estudio',
            },
        ),
        migrations.CreateModel(
            name='Imagen_Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('slug', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pachaqtec.producto')),
                ('tipo_imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pachaqtec.tipo_imagen')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imagenes del Producto',
            },
        ),
    ]
