<<<<<<< HEAD
# Generated by Django 3.1.3 on 2020-11-27 01:00
=======
# Generated by Django 3.1.3 on 2020-11-27 00:51
>>>>>>> 96e4e185e2fbc399bdb1caae5e8d635276378b27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtec', '0002_imagen_producto_plan_estudio_producto_sub_unidad_estudio_unidad_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='2020-11-26'),
            preserve_default=False,
        ),
    ]
