# Generated by Django 3.1.3 on 2020-11-27 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtec', '0004_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Estudio_Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField(default='X')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pachaqtec.plan_estudio')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pachaqtec.producto')),
            ],
        ),
    ]
